###服务端口号
server:
  port: 8060
###服务名称
spring:
  application:
    name: zk-order
  cloud:
    zookeeper:
    ###注册到zookeeper地址
      connect-string: 127.0.0.1:2181
      discovery:
        register: true
        enabled: true
        instance-id: 2
        root: /zk-spring-cloud