###注册 中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
server:
  port: 80
###网关名称
spring:
  application:
    name: service-zuul
  cloud:
      config:
      ####读取后缀
        profile: dev
        ####读取config-server注册地址
        discovery:
          service-id: config-server
          enabled: true
### 配置网关反向代理
#zuul:
#  routes:
    #定义服务转发规则
#    api-a:
     ###当客户端请求127.0.0.1;80/api-member/  开头得都会转发到会员服务
#      path: /api-member/**
      #服务别名 zuul网关默认整合ribbon,自动实现负载均衡轮询效果
#      serviceId: app-itmayiedu-member
#    api-b:
        ### 以 /api-order/访问转发到订单服务
#      path: /api-order/**
#      serviceId: app-itmayiedu-order

###开启所有监控中心接口
management:
  endpoints:
    web:
      exposure:
        include: "*"