#单点 eurekap配置
server:
  port: 9100
#集群一定要定义服务名称，而且都要一致
spring:
  application:
     name: eureka-server
eureka:
  instance:
    #注册中心ip地址
    hostname: 127.0.0.1
  client:
    serviceUrl:
      #注册地址
      defaultZone: http://${eureka.instance.hostname}:8100/eureka/
    #因为自己是注册中心，是否需要将自己注册给自己的注册中心（集群的时候需要设为true）
    register-with-eureka: true
    #因为自己是注册中心，不需要去检索服务信息
    fetch-registry: true
  server:
    # 测试时关闭自我保护机制，保证不可用服务及时踢出
    enable-self-preservation: false
    ##剔除失效服务间隔
    eviction-interval-timer-in-ms: 2000